### ISSUE TITLE
What is the license for this repository, please?

### ISSUE THREAD

**Issue by zeritonius** [abjennings/gmail-backup#11]
What is the license for this repository, please?

Also, I wanted to ask what license the JavaScript code from these pages has:
http://ajennings.net/blog/a-million-digits-of-pi-in-9-lines-of-javascript.html
http://ajennings.net/pi.html

Thank you.

**Comment by abjennings** [comment]
I added an MIT license.

The code on the Pi pages will also be MIT-licensed. I will try to add it soon.

**Comment by abjennings** [comment]
The Pi pages on my blog have been updated as well.
