### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by Xeoncross** [abjennings/gmail-backup#9]
```
Traceback (most recent call last):
  File "dobackup.py", line 77, in <module>
    do_backup()
  File "dobackup.py", line 46, in do_backup
    svr.login(user, pwd)
  File "/2.7/lib/python2.7/imaplib.py", line 520, in login
    raise self.error(dat[-1])
imaplib.error: [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```

**Comment by abjennings** [comment]
It just worked again for me, but Google login is finicky.  I have 2FA turned on, so I've always had to use "app passwords" for my script:
https://myaccount.google.com/apppasswords

If you don't have 2FA turned on, you might have to turn on the setting to "allow less secure apps":
https://www.google.com/settings/security/lesssecureapps
